kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-pv1-pvc1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: local-storage
  selector:
    matchLabels:
      id: "node1-disk1"	
