apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv1
  labels:
    type: nfs-pv
spec:
  storageClassName: nfs-storage
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs1
    path: "/var/nfs/share1"
