apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-nfs-deploy
  labels:
   app: nginx-nfs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-nfs
  template:
    metadata:
      labels:
        app: nginx-nfs
    spec:
      volumes:
      - name: www-nfs
        persistentVolumeClaim:
          claimName: nfs-pv1-pvc1
      containers:
      - image: nginx
        name: nginx-nfs
        volumeMounts:
        - name: www-nfs
          mountPath: /usr/share/nginx/html
