apiVersion: v1
kind: Pod
metadata:
  name: nginx-hostpath1

spec:
  nodeName: worker1
  containers:
  - image: nginx
    name: nginx-hostpath1
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: node1-dir1
  volumes:
  - name: node1-dir1
    hostPath:
      # directory location on host
      path: /var/hostpath/www
      # this field is optional
      type: Directory
