apiVersion: apps/v1
kind: Deployment
metadata:
  name: websrv-deployment
  labels:
    app: websrv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: websrv
  template:
    metadata:
      labels:
        app: websrv
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
